config/routes.rb
Rails.application.routes.draw do
  resources :books
  root :to => 'homes#top'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'bookss#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
       redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'Book was successfully created.'
   else
      render :edit
   end 
  end 

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
 <% if @book.errors.any? %>
<div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
    <ul>
     <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
  </ul>
</div>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
 <% if @book.errors.any? %>
   <div class="field">
 <div class="error_field">
   <label>Title</label>
   </div>
   <div class="error_field">
   <%= f.text_field :title %>
   </div>
 </div>

 <div class="field">
 <div class="error_field">
    <label>Body</label>
   </div>
 <div class="error_field">
   <%= f.text_area :body %>
 </div>
 </div>

 <div class="actions">
 <%= f.submit 'Update Book' %>
</div>
   <% else %>

   <div class="field">
   <label>Title</label>
   <%= f.text_field :title %>
 </div>

 <div class="field">
    <label>Body</label>
   <%= f.text_area :body %>
 </div>

 <div class="actions">
   <%= f.submit 'Update Book' %>
   </div>
 <% end %>
<% end %>

<span><%= link_to 'Show', "/books/#{@book.id}" %></span>
|
<span><%= link_to 'Back', "/books" %></span>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
    <thead>
        <th>Title</th>
        <th>Body</th>
        <th colspan="3"></th>
    </thead>
    <% @books.each do |book| %>
    <tbody>
       <td> <%= book.title %> </td>
       <td><%= book.body %> </td>
       <td><%= link_to 'Show', "/books/#{book.id}" %></td>
       <td><%= link_to 'Edit',edit_book_path(book.id) %></td>
       <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
    <% end %>
    </tbody>
</table>

<h2>New book</h2>
 <% if @book.errors.any? %>
<div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
    <ul>
     <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
  </ul>
</div>
<% end %>

<%= form_with model: Book.new do |f| %>
 <% if @book.errors.any? %>
 <div class="field">
 <div class="error_field">
 <label>Title</label>
   </div>
   <div class="error_field">
   <%= f.text_field :title %>
   </div>
 </div>

 <div class="field">
 <div class="error_field">
   <label>Body</label>
   </div>
 <div class="error_field">
   <%= f.text_area :body %>
 </div>
 </div>

 <div class="actions">
   <%= f.submit 'Create Book' %>
</div>
   <% else %>

   <div class="field">
   <label>Title</label>
   <%= f.text_field :title %>
 </div>

 <div class="field">
   <label>Body</label>
   <%= f.text_area :body %>
 </div>

 <div class="actions">
   <%= f.submit 'Create Book' %>

 </div>
 <% end %>
<% end %>

app/views/books/show.html.erb
<div class="notice" >
 <%= flash[:notice] %>
 </div>
 
<p>
  <d>Title:</d><%= @book.title %>
  </p>


<p>
  <d>Body:</d><%= @book.body %>
  </p>

<span><%= link_to 'Edit',edit_book_path(@book.id) %></span>
|
<span><%= link_to 'Back', "/books" %></span>

app/views/homes/top.html.erb
<h1>ようこそ　Bookersへ！</h1>
<p><b>Bookers</b>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<%= link_to 'start', "/books" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>